#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TrucosAgeOEmp.Resource", IsApplication=true)]

namespace TrucosAgeOEmp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int age2hd = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int btnJuego = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int btnMapa = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int btnPersonajes = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int btnRecursos = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int imageAge2Hd = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int tableLayout1 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int tableRow1 = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int tableRow2 = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int tableRow3 = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int tableRow4 = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int tableRow5 = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int tableRow6 = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int tableRow7 = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int tableRow8 = 2131034134;
			
			// aapt resource value: 0x7f05000b
			public const int txtComida = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int txtInstrucciones = 2131034118;
			
			// aapt resource value: 0x7f05000f
			public const int txtMadera = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int txtMenu = 2131034113;
			
			// aapt resource value: 0x7f050013
			public const int txtOro = 2131034131;
			
			// aapt resource value: 0x7f050009
			public const int txtRecursosComida = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int txtRecursosMadera = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int txtRecursosOro = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int txtRecursosRoca = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int txtRoca = 2131034135;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Recursos = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int ButtonJuego = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int ButtonMapa = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ButtonPersonajes = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int ButtonRecursos = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int Comida = 2130968583;
			
			// aapt resource value: 0x7f040000
			public const int Instrucciones = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int Madera = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int Oro = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Roca = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int txtMenu = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
